package mm.core;

import static mm.core.MMCore.modid;
import static mm.core.MMCore.name;
import static mm.core.MMCore.version;

import java.util.ArrayList;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import mm.client.gui.GuiHandler;
import mm.common.lib.CreativeTabMixedMagic;
import mm.init.MMBlocks;
import mm.init.MMEnchanctments;
import mm.init.MMItems;
import mm.init.MMRecipes;
import mm.init.MMThaumonomicon;
import mm.network.proxy.MMServer;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = modid, version = version, name = name)
public class MMCore {
	
	public static final String modid = "mixedmagic";
	public static final String version = "1.0.1710.0";
	public static final String name = "Mixed Magic";
	public static final String serverProxy = "mm.network.proxy.MMServer";
	public static final String clientProxy = "mm.network.proxy.MMClient";
	public static final int guiIDLPulverizer = 0;
	public static CreativeTabs tabMM = new CreativeTabMixedMagic(CreativeTabs.getNextID(), "mixedmagic");
	
	@SidedProxy(serverSide = serverProxy, clientSide = clientProxy)
	public static MMServer proxy;
	
	public static MMCore instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		System.out.println("[INFO][MixedMagic] Next text with @MixedMagic == For developers. ");
		System.out.println("[MixedMagic] Loading preInit piece of mod.");
		System.out.println("[MixedMagic][PREINIT] LOADING <MMItems> | <MMBlocks> | <MMEnchantments> | LOADING PROXY ");
		instance = this;
		setupModInfo(event.getModMetadata());
		MMItems.setup();
		MMBlocks.setup();
		MMEnchanctments.setup();
		System.out.println("[MixedMagic][PREINIT][PROXY][VOID] LOADING <registerRenderInformation> | <getClientGuiElement> ");
		proxy.registerRenderInformation();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
		System.out.println("[MixedMagic] Loading init piece of mod.");
	    NetworkRegistry.INSTANCE.registerGuiHandler(instance, new GuiHandler());
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		System.out.println("[MixedMagic] Loading postInit piece of mod.");
		System.out.println("[MixedMagic][POSTINIT] LOADING <MMRecipes> | <MMThaumonomicon> - void {setup} ");
		MMRecipes.setup();
		MMThaumonomicon.setup();
	}
	
	public void setupModInfo(ModMetadata meta)
	{
		meta.autogenerated = false;
		meta.modId = modid;
		meta.version = version;
		meta.name = name;
		meta.description = "This is mod of mixed magic .-.";
		ArrayList<String> authors = new ArrayList<String>();
		authors.add("JakiHappyCity");
		meta.authorList = authors;
		meta.url = "";
		meta.logoFile = "logo.png";
	}
	
}
