package mm.core;

import static mm.core.MMCore.*;

import java.util.ArrayList;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import mm.common.lib.CreativeTabMixedMagic;
import mm.init.MMBlocks;
import mm.init.MMEnchanctments;
import mm.init.MMItems;
import mm.init.MMRecipes;
import mm.init.MMThaumonomicon;
import mm.network.proxy.MMClient;
import mm.network.proxy.MMServer;
import net.minecraft.creativetab.CreativeTabs;

@Mod(modid = modid, version = version, name = name)
public class MMCore {
	
	public static final String modid = "mixedmagic";
	public static final String version = "1.0.1710.0";
	public static final String name = "Mixed Magic";
	public static final String serverProxy = "mm.network.proxy.MMServer";
	public static final String clientProxy = "mm.network.proxy.MMClient";
	public static final Logger log = LogManager.getLogger("MIXEDMAGIC");
	public static CreativeTabs tabMM = new CreativeTabMixedMagic(CreativeTabs.getNextID(), "mixedmagic");
	
	@SidedProxy(serverSide = serverProxy, clientSide = clientProxy)
	public static MMServer proxy;
	
	public static MMCore instance;
	
	@EventHandler
	public void preInit(FMLPreInitializationEvent event)
	{
		log.info("Loading Mixed Magic");
		instance = this;
		setupModInfo(event.getModMetadata());
		MMItems.setup();
		MMBlocks.setup();
		MMEnchanctments.setup();
		proxy.registerRenderInformation();
	}
	
	@EventHandler
	public void init(FMLInitializationEvent event)
	{
	    NetworkRegistry.INSTANCE.registerGuiHandler(instance, new MMClient());
	}
	
	@EventHandler
	public void postInit(FMLPostInitializationEvent event)
	{
		MMRecipes.setup();
		MMThaumonomicon.setup();
	}
	
	public void setupModInfo(ModMetadata meta)
	{
		meta.autogenerated = false;
		meta.modId = modid;
		meta.version = version;
		meta.name = name;
		meta.description = "This is mod of mixed magic .-.";
		ArrayList<String> authors = new ArrayList<String>();
		authors.add("JakiHappyCity");
		meta.authorList = authors;
		meta.url = "";
		meta.logoFile = "logo.png";
	}
	
}
